# Generated by Django 5.1.3 on 2024-11-28 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basket',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
