# Generated by Django 5.1.3 on 2024-11-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_basket'),
        ('transaction', '0002_transaction_user_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskets', to='transaction.transaction'),
        ),
    ]
